export const types = {
  FETCHING_WALLET_START: 'FETCHING_WALLET_START',
  FETCHING_WALLET_SUCCESS: 'FETCHING_WALLET_SUCCESS',
  FETCHING_EXCHANGE_RATES_START: 'FETCHING_EXCHANGE_RATES_START',
  FETCHING_EXCHANGE_RATES_SUCCESS: 'FETCHING_EXCHANGE_RATES_SUCCESS',
  SET_CURRENCY_FROM: 'SET_CURRENCY_FROM',
  SET_CURRENCY_TO: 'SET_CURRENCY_TO',
  SELECT_AMOUNT_FROM: 'SELECT_AMOUNT_FROM',
  SELECT_AMOUNT_TO: 'SELECT_AMOUNT_TO',
};