export const types = {
  FETCHING_WALLET_START: 'FETCHING_WALLET_START',
  FETCHING_WALLET_SUCCESS: 'FETCHING_WALLET_SUCCESS',
  FETCHING_EXCHANGE_RATES_START: 'FETCHING_EXCHANGE_RATES_START',
  FETCHING_EXCHANGE_RATES_SUCCESS: 'FETCHING_EXCHANGE_RATES_SUCCESS',
};